
services:
  backend:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    ports:
      - "9000:8000"
    volumes:
      - ./src/api:/app/api
    depends_on:
      - qdrant

  frontend:
    build:
      context: .
      dockerfile: src/gui/Dockerfile
    ports:
      - "3000:8501"
    volumes:
      - ./src/gui:/app/gui
    stdin_open: true
    tty: true

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage:
